### ISSUE TITLE
Contact Travis about caching

### ISSUE THREAD

**Issue by mzayats** [libreswitch/libreswitch#11]

**Comment by mzayats** [comment]
Posted the question to Travis support.

**Comment by vitalivanov** [comment]
@mzayats @ddompe 
Caching for travis is described here:
https://docs.travis-ci.com/user/caching/

**Comment by vitalivanov** [comment]
Seems like @ddompe already added it by the following travis settings:

script: cd $TRAVIS_BUILD_DIR/build/sstate-cache/ && rsync -avzL --progress ?? universal libreswitch-ci@yocto.libreswitch.org:/data/yocto-cache/sstate-cache/

I enabled in my libreswitch clone repo all platforms and would see what it taken to build all of them.
