### ISSUE TITLE
Migrate Taiga issues to Github

### ISSUE THREAD

**Issue by mzayats** [libreswitch/libreswitch#12]

**Comment by mzayats** [comment]
Will start working on it on Jan. 3rd.

**Comment by mzayats** [comment]
All issues are pulled from Taiga, building a script to import into Github.

**Comment by vitalivanov** [comment]
Main thing is to pull from Taiga to CSV. Only OpenSwitch admin @ Taiga can do that.

**Comment by mzayats** [comment]
I have it in JSON format, though all JSON tools complain that it's broken :)

**Comment by mzayats** [comment]
All Open/Assigned issues from OPS Taiga are migrated. Every issue has a link to the original Taiga issue.
