### ISSUE TITLE
Get approval from BCM to host OpenNSL binaries by ourselves

### ISSUE THREAD

**Issue by ddompe** [libreswitch/libreswitch#5]

**Comment by vitalivanov** [comment]
Email discussion started with Broadcom folks...

**Comment by vitalivanov** [comment]
I've got approval from Broadcom OpenNSL PLM Ashok Raman that we can host latest OpenNSL binaries at libreswitch domain:
opennsl-3.2.0.1-cdp-as5712-6217657.tar.bz2
opennsl-3.2.0.1-cdp-as6712-6217657.tar.bz2
opennsl-3.2.0.1-cdp-as7712-6217657.tar.bz2

@ddompe can you pls copy binaries to libreswitch.org?

**Comment by vitalivanov** [comment]
Packages are placed at:
https://libreswitch.org/opennsl
Only version 3.2.0.1 is used.

Pull request if here:
https://github.com/libreswitch/libreswitch/pull/424
