### ISSUE TITLE
New build working on AS5712

### ISSUE THREAD

**Issue by ddompe** [libreswitch/libreswitch#7]
Test code in AS5712

**Comment by vitalivanov** [comment]
@bluecmd 
@ddompe mentioned that you have one of as5712 HW.
We need to check that something that we build here is working on actual HW.
Can you pls check this out?

**Comment by bluecmd** [comment]
Sure. Just shoot me the build artifact and I can ONIE it up.

**Comment by vitalivanov** [comment]
Sure, it's now in pull request:
https://github.com/libreswitch/libreswitch/pulls
Once it's CI'ed and merged to master, we can get an ONIE image from there.

**Comment by vitalivanov** [comment]
@bluecmd I just uploaded ONIE binary to my google drive to try for you.

**Comment by bluecmd** [comment]
It's about 1.6 years too later, but I'm pretty sure I never saw the notification and thus never got to it :/. Oh well.
